name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate CSS file
        run: |
          # Check that CSS file exists
          if [ ! -f "design-tokens.css" ]; then
            echo "❌ Missing required file: design-tokens.css"
            exit 1
          fi
          echo "✅ CSS file present"

      - name: Check file size
        run: |
          # Ensure CSS file isn't too large
          MAX_SIZE=100000 # 100KB
          SIZE=$(stat -f%z "design-tokens.css" 2>/dev/null || stat -c%s "design-tokens.css")
          if [ $SIZE -gt $MAX_SIZE ]; then
            echo "⚠️  Warning: design-tokens.css is larger than 100KB ($SIZE bytes)"
          else
            echo "✅ design-tokens.css size: $SIZE bytes"
          fi

      - name: Validate package.json
        run: |
          # Check package.json is valid JSON
          node -e "JSON.parse(require('fs').readFileSync('package.json', 'utf8'))"
          echo "✅ package.json is valid"
          
          # Check required fields
          node -e "
            const pkg = require('./package.json');
            const required = ['name', 'version', 'description', 'main', 'files'];
            const missing = required.filter(field => !pkg[field]);
            if (missing.length) {
              console.error('❌ Missing required fields:', missing.join(', '));
              process.exit(1);
            }
            console.log('✅ All required fields present');
          "